server:
  host: '127.0.0.1'
  port: 10808
db:
  cve_file: 'data/cve.db'
  package_file: 'data/package.db'
  session_file: 'data/session.db'
debian_tracker:
  base_url: 'https://security-tracker.debian.org/tracker'
  home_url: 'https://security-tracker.debian.org/tracker/status/release/stable'
ldap:
  host: ''
  port: 339
  dn: ''
  password: ''
  user_search: ''
  group_search: ''
packages_file: "data/packages.list"
